### ISSUE TITLE
Доступ к репозиторию.

### ISSUE THREAD

**Issue by NKhashchanov** [ivanmanokhin/sqlp-netology#1]
Добрый день, Иван.
Могу попросить Вас закрыть доступ к данному репозиторию, если есть такая возможность. 
Другие учащиеся используют Ваши решения вместо самостоятельной проработки заданий.
Заранее большое спасибо!

**Comment by ivanmanokhin** [comment]
Добрый день!
Извините, что так долго не отвечал, давно не заходил на GitHub. Да, конечно закрою.
